version: '2'

networks:
  default-network:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
    networks:
      - default-network

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql
      - redis
    container_name: docs_generator_php_fpm
    networks:
      - default-network

  job-worker:
    build:
      context: .
      dockerfile: deployment/local/docker/job-worker/Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - default-network
    depends_on:
      - pgsql
      - redis
      - php-fpm
    container_name: docs_generator_job_worker

  pgsql:
    image: postgres:11.3
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./persistent_data/pgsql:/var/lib/postgresql/data
    networks:
      - default-network

  pgsql_testing:
    image: postgres:11.3
    ports:
      - "${DOCKER_PGSQL_TESTING_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_TESTING_DATABASE}
      POSTGRES_USER: ${DB_TESTING_USERNAME}
      POSTGRES_PASSWORD: ${DB_TESTING_PASSWORD}
    networks:
      - default-network

  redis:
    image: redis:4.0
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    networks:
      - default-network
