swagger: "2.0"
info:
  title: "Docs generator API"
  description: "Documentation for Docs generator API"
  version: "0.5"
schemes:
  - "https"
host: 127.0.0.1:31080
basePath: /api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  ##############################
  # Auth requests              #
  ##############################

  /v1/auth/register:
    post:
      tags:
        - "auth"
      summary: "Register new user"
      description: ""
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
        - name: "RegisterRequestBody"
          in: "body"
          description: "Register request body"
          required: true
          schema:
            $ref: "#/definitions/RegisterRequestModel"
      responses:
        201:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        422:
          description: "Validation error"
          schema:
            $ref: "#/definitions/DefaultValidationErrorResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"

  /v1/auth/login:
    post:
      tags:
        - "auth"
      summary: "Login user"
      description: ""
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
        - name: "LoginRequestBody"
          in: "body"
          description: "Login request body"
          required: true
          schema:
            $ref: "#/definitions/LoginRequestModel"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/LoginResponseModel"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"
        422:
          description: "Validation error"
          schema:
            $ref: "#/definitions/DefaultValidationErrorResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"

  ##############################
  # Current user requests      #
  ##############################

  /v1/account/user:
    get:
      tags:
        - "user"
      security:
        - bearerAuth: [ ]
      summary: "Get current user info"
      description: ""
      produces:
        - "application/json"
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/UserDetailDataResponseModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"
    put:
      tags:
        - "user"
      security:
        - bearerAuth: [ ]
      summary: "Update current user"
      description: ""
      produces:
        - "application/json"
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
        - name: "UpdateUserRequestBody"
          in: "body"
          description: "Update user request body"
          required: true
          schema:
            $ref: "#/definitions/UpdateUserRequestModel"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        422:
          description: "Validation error"
          schema:
            $ref: "#/definitions/DefaultValidationErrorResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"

  ####################################
  # Document templates requests      #
  ####################################

  /v1/account/document-templates:
    get:
      tags:
        - "document templates"
      security:
        - bearerAuth: [ ]
      summary: "Get document templates list"
      description: ""
      produces:
        - "application/json"
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
        - in: "query"
          name: "limit"
          type: "integer"
          description: "Limit of items in response"
        - in: "query"
          name: "offset"
          type: "integer"
          description: "Offset of items in response"
        - in: "query"
          name: "sort_by"
          type: "string"
          description: "Sort by column"
          enum:
            - id
            - name
            - created_at
        - in: "query"
          name: "sort_direction"
          type: string
          description: "Sort direction"
          enum:
            - asc
            - desc
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/DocumentTemplatesListResponseModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        422:
          description: "Validation error"
          schema:
            $ref: "#/definitions/DefaultValidationErrorResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"
    post:
      tags:
        - "document templates"
      security:
        - bearerAuth: [ ]
      summary: "Create document template"
      description: ""
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
        - name: "CreateDocumentTemplateRequestBody"
          in: "body"
          description: "Create document template request body"
          required: true
          schema:
            $ref: "#/definitions/CreateDocumentTemplateRequestModel"
      responses:
        201:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        422:
          description: "Validation error"
          schema:
            $ref: "#/definitions/DefaultValidationErrorResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"

  /v1/account/document-templates/{document_template}:
    delete:
      tags:
        - "document templates"
      security:
          - bearerAuth: [ ]
      summary: "Delete specific document template"
      description: ""
      produces:
        - "application/json"
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: X-Locale
          type: string
          enum:
            - ru
            - en
        - in: path
          name: document_template
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/NotFoundResponseModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ServerErrorResponseModel"

definitions:

  ##############################
  # Requests                   #
  ##############################

  RegisterRequestModel:
    type: "object"
    required:
      - "email"
      - "password"
      - "password_confirmation"
    properties:
      email:
        type: "string"
      password:
        type: "string"
      password_confirmation:
        type: "string"
      company_name:
        type: "string"

  LoginRequestModel:
    type: "object"
    required:
      - "email"
      - "password"
    properties:
      email:
        type: "string"
      password:
        type: "string"

  UpdateUserRequestModel:
    type: "object"
    required:
      - "email"
    properties:
      email:
        type: "string"
      password:
        type: "string"
      password_confirmation:
        type: "string"
      first_name:
        type: "string"
      surname:
        type: "string"
      last_name:
        type: "string"

  CreateDocumentTemplateRequestModel:
    type: "object"
    required:
      - "name"
      - "file"
    properties:
      name:
        type: "string"
      file:
        $ref: "#/definitions/CreateFileRequestModel"

  CreateFileRequestModel:
    type: "object"
    required:
      - "name"
      - "mime"
      - "content"
    properties:
      name:
        type: "string"
      mime:
        type: "string"
      content:
        type: "string"

  ##############################
  # Responses                  #
  ##############################

  SimpleSuccessResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"

  UnauthorizedResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"

  ForbiddenResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"

  NotFoundResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"

  DefaultValidationErrorResponseModel:
    type: "object"
    properties:
      errors:
        type: "object"

  ServerErrorResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"

  LoginResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"
      token:
        type: "string"

  UserDetailDataResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      message:
        type: "string"
      user:
        $ref: "#/definitions/UserDetailResponseModel"

  UserDetailResponseModel:
    type: "object"
    properties:
      id:
        type: "integer"
      email:
        type: "string"
      first_name:
        type: "string"
      surname:
        type: "string"
      last_name:
        type: "string"

  DocumentTemplatesListResponseModel:
    type: "object"
    properties:
      success:
        type: "boolean"
      count:
        type: "integer"
      items:
        type: "array"
        items:
          $ref: "#/definitions/DocumentTemplateResponseModel"

  DocumentTemplateResponseModel:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      created_at:
        type: "string"
      file:
        $ref: "#/definitions/FileResponseModel"

  FileResponseModel:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      mime:
        type: "string"
      url:
        type: "string"
